djangoExam/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('sali_de_curs.urls')),
    path('', include('userextend.urls')),
    path('', include('programare_examene.urls')),



    path('', include('django.contrib.auth.urls'))
]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path('', views.HomeTemplateView.as_view(), name='home-page')
]

programare_examene/urls.py
from django.urls import path

from programare_examene import views

urlpatterns = [
    path('schedule_classroom/', views.ScheduleExamClassroomCreateView.as_view(), name='schedule-classroom'),
    path('get_available_classrooms/', views.get_available_classrooms, name='get-available-classrooms'),  # for AJAX request
    path('schedule_exam/', views.ScheduleExamCreateView.as_view(), name='schedule-exam'),

]

programare_examene/models.py
from datetime import time

from django.contrib.auth.models import User
from django.db import models

from sali_de_curs.models import Classroom


class ScheduleExam(models.Model):
    nume_prenume = models.CharField(max_length=35)
    specializarea = models.CharField(max_length=50)
    numele_disciplinei = models.CharField(max_length=50)
    anul = models.CharField(max_length=6)
    grupa = models.CharField(max_length=30, null=True, blank=True)
    observatii = models.CharField(max_length=20, null=True, blank=True)
    forma_examinare = models.CharField(max_length=5, null=True, blank=True)

    exam_dates = models.ManyToManyField('ScheduleExamClassroom')
    feedback_rezultate = models.CharField(max_length=60, null=True, blank=True)


class ScheduleExamClassroom(models.Model):
    data = models.DateField()
    ora_incepere = models.TimeField()
    durata = models.DurationField()
    nr_studenti = models.PositiveIntegerField()
    sala_examen = models.ForeignKey(Classroom, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        formatted_ora_incepere = self.ora_incepere.strftime('%H:%M')
        formatted_date = self.data.strftime('%d/%m')
        return f'Data: {formatted_date}, Ora: {formatted_ora_incepere}, Sala: {self.sala_examen}'

programare_examene/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MaxValueValidator
from django.forms import TextInput, NumberInput, Textarea, DateInput, TimeInput, Select, MultipleChoiceField

from programare_examene.models import ScheduleExam, ScheduleExamClassroom
from sali_de_curs.models import Classroom


class ScheduleExamForm(forms.ModelForm):
    class Meta:
        model = ScheduleExam
        fields = '__all__'
        widgets = {
            'nume_prenume': TextInput(attrs={'placeholder': 'Introduceti numele si prenumele dvs.', 'class': 'form-control'}),
            'specializarea': TextInput(attrs={'placeholder': 'Introduceti specializarea', 'class': 'form-control'}),
            'numele_disciplinei': TextInput(attrs={'placeholder': 'Introduceti numele disciplinei', 'class': 'form-control'}),
            'anul': TextInput(attrs={'placeholder': 'Introduceti anul', 'class': 'form-control'}),
            'grupa': TextInput(attrs={'placeholder': 'Introduceti grupa', 'class': 'form-control'}),
            'observatii': TextInput(attrs={'placeholder': 'Introduceti observatii', 'class': 'form-control'}),
            'forma_examinare': TextInput(attrs={'placeholder': 'Introduceti forma de examinare', 'class': 'form-control'}),
            'feedback_rezultate': TextInput(attrs={'placeholder': 'Modalitatea si/sau data de feedback rezultate', 'class': 'form-control'}),
        }
        exam_dates = forms.ModelMultipleChoiceField(
            queryset=ScheduleExamClassroom.objects.all(),
            widget=forms.CheckboxSelectMultiple(attrs={'class': 'form-select'}),
            validators=[
                MinValueValidator(limit_value=2, message='Va rog selectati 2 clase.'),
                MaxValueValidator(limit_value=2, message='Va rog nu selectati mai mult de 2 clase.')
            ]
        )

        labels = {
            'exam_dates': 'Clase programate'
        }


class SalaExamenWidget(forms.Select):
    def get_context(self, name, value, attrs):
        context = super().get_context(name, value, attrs)
        widget = context['widget']

        # Add the custom attributes within the 'attrs' dictionary.
        widget['attrs']['data-data-url'] = '/get_available_classrooms/'
        widget['attrs']['data-depended-fields'] = 'data ora_incepere durata nr_studenti'

        # Set the 'class' attribute for styling.
        widget['attrs']['class'] = 'form-control'

        return context


class ScheduleExamClassroomForm(forms.ModelForm):
    NR_STUDENTS = [(space, space) for space in Classroom.objects.values_list('space', flat=True).distinct()]
    nr_studenti = forms.ChoiceField(choices=NR_STUDENTS, widget=forms.Select(attrs={'class': 'form-control'}))

    sala_examen = forms.ModelChoiceField(
        queryset=Classroom.objects.all(),
        widget=SalaExamenWidget,
    )

    class Meta:
        model = ScheduleExamClassroom
        fields = ['data', 'ora_incepere', 'durata', 'nr_studenti', 'sala_examen']
        widgets = {
            'data': DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'ora_incepere': TimeInput(attrs={'class': 'form-control', 'type': 'time'}),
            'durata': TimeInput(attrs={'class': 'form-control', 'type': 'time'})
        }

programare_examene/views.py
from datetime import datetime, timedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.views.generic import CreateView

from programare_examene.forms import ScheduleExamClassroomForm, ScheduleExamForm
from programare_examene.models import ScheduleExamClassroom, ScheduleExam
from sali_de_curs.models import Classroom


class ScheduleExamCreateView(LoginRequiredMixin, CreateView):
    model = ScheduleExam
    form_class = ScheduleExamForm
    template_name = 'programare_examene/creare_programare.html'
    success_url = reverse_lazy('home-page')

    def form_valid(self, form):
        selected_exam_dates = form.cleaned_data['exam_dates']
        available_exam_dates = ScheduleExamClassroom.objects.filter(
            user=self.request.user
        ).exclude(id__in=[obj.id for obj in selected_exam_dates])
        form.fields['exam_dates'].queryset = available_exam_dates
        form.instance.user = self.request.user
        return super().form_valid(form)


class ScheduleExamClassroomCreateView(LoginRequiredMixin, CreateView):
    model = ScheduleExamClassroom
    form_class = ScheduleExamClassroomForm
    template_name = 'programare_examene/creare_programare_clasa.html'
    success_url = reverse_lazy('home-page')

    def form_valid(self, form):
        if form.is_valid():
            schedule_exam = form.save(commit=False)
            schedule_exam.user = self.request.user
            schedule_exam.save()
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Disable the classroom fields until the user has selected the dates and hours.
        context['form'].fields['sala_examen'].disabled = True

        return context


def get_available_classrooms(request):
    # Get the selected values from the GET request parameters.
    selected_data = request.GET.get('data')
    selected_ora_incepere = request.GET.get('ora_incepere')
    selected_durata = request.GET.get('durata')
    selected_nr_studenti = request.GET.get('nr_studenti')

    # Parse selected_data and selected_ora_incepere to datetime objects.
    selected_data = datetime.strptime(selected_data, '%Y-%m-%d')
    selected_ora_incepere = datetime.strptime(selected_ora_incepere, '%H:%M')

    hours, minutes = map(int, selected_durata.split(':'))
    selected_durata = timedelta(hours=hours, minutes=minutes)

    end_time = selected_ora_incepere + selected_durata

    if selected_durata.total_seconds() >= 12 * 3600:
        query_part1 = Q(ora_incepere__gte=end_time)

        query_part2 = Q(ora_incepere__lt=selected_ora_incepere)

        already_booked_filter = query_part1 | query_part2
    else:
        already_booked_filter = Q(
            Q(ora_incepere__lte=selected_ora_incepere, ora_incepere__gt=end_time) |
            Q(ora_incepere__lt=end_time, ora_incepere__gte=selected_ora_incepere - timedelta(hours=1))
        )

    booked_classrooms = ScheduleExamClassroom.objects.filter(
        data=selected_data,
        sala_examen__space=selected_nr_studenti
    ).filter(already_booked_filter)

    booked_classrooms_ids = booked_classrooms.values_list('sala_examen_id', flat=True)

    available_classrooms = Classroom.objects.filter(
        space=selected_nr_studenti
    ).exclude(id__in=booked_classrooms_ids)
    # Convert the filtered classrooms to a JSON-friendly format.
    classrooms_data = [{
        'id': classroom.id,
        'name': classroom.name,
    } for classroom in available_classrooms]

    print(f"This is the classrooms_data: {classrooms_data}")
    # Return the JSON response with the available classrooms.
    return JsonResponse({'classrooms': classrooms_data})

templates/programare_examene/creare_programare.html
{% extends 'base.html' %}
{% block title %} Examen nou {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card" data-bs-theme="dark">
                    <div class="card-header">
                        <h3 class="text-center">Programati un examen</h3>
                    </div>
                    <form method="post">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-success">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/programare_examene/creare_programare_clasa.html
{% extends 'base.html' %}
{% block title %} New classroom {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card" data-bs-theme="dark">
                    <div class="card-header">
                        <h3 class="text-center">Programati o sala de curs</h3>
                    </div>
                    <form method="post">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-success">Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Include jQuery -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script>
        $(document).ready(function () {
            var allFieldsCompleted = false
            // Capture changes in dependent fields (data, ora_incepere, durata, nr_studenti).
            $('#id_data, #id_ora_incepere, #id_durata, #id_nr_studenti').on('change', function () {
                // Gather selected values from dependent fields.
                var selectedData = $('#id_data').val();
                var selectedOraIncepere = $('#id_ora_incepere').val();
                var selectedDurata = $('#id_durata').val();
                var selectedNrStudenti = $('#id_nr_studenti').val();

                allFieldsCompleted = selectedData && selectedOraIncepere && selectedDurata && selectedNrStudenti;

                // Make an AJAX request to get available classrooms based on selected values.
                if (allFieldsCompleted) {
                    $.ajax({
                        url: $('#id_sala_examen').data('data-url'),
                        data: {
                            data: selectedData,
                            ora_incepere: selectedOraIncepere,
                            durata: selectedDurata,
                            nr_studenti: selectedNrStudenti,
                        },
                        success: function (data) {
                            console.log('Received data:', data)
                            // Populate the 'sala_examen' select element with available options.
                            var salaExamenSelect = $('#id_sala_examen');
                            console.log('salaExamenSelect:', salaExamenSelect)
                            salaExamenSelect.empty();

                            // Add available options from the AJAX response.
                            $.each(data.classrooms, function (index, classroom) {
                                salaExamenSelect.append(
                                    new Option(classroom.name, classroom.id, false, false)
                                );
                            });
                        }
                    });
                }
            });
        });
    </script>

    <script>
        function enableSalaExamenFields() {
            // Get the sala examen fields.
            const salaExamenField = document.querySelector('#id_sala_examen');

            // Get the date and time fields for sala examen 1.
            const dataExamenField = document.querySelector('#id_data');
            const oraIncepereField = document.querySelector('#id_ora_incepere');
            const durataField = document.querySelector('#id_durata');
            const nr_studentiField = document.querySelector('#id_nr_studenti');


            // Enable the sala examen fields only if all of the date and time fields are selected and the date has been changed and the time has been changed.
            salaExamenField.disabled = !dataExamenField.value || !oraIncepereField.value || !durataField.value || !nr_studentiField.value
        }

        // Listen for the change event on all of the date and time fields.
        document.querySelector('#id_data').addEventListener('change', enableSalaExamenFields);
        document.querySelector('#id_ora_incepere').addEventListener('change', enableSalaExamenFields);
        document.querySelector('#id_durata').addEventListener('change', enableSalaExamenFields);
        document.querySelector('#id_nr_studenti').addEventListener('change', enableSalaExamenFields);

    </script>
{% endblock %}